stages:
- prepare
- build
- test

variables:
  DOCKER_FILE: Dockerfile
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  GIT_SUBMODULE_STRATEGY: normal
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

.prepare:docker: &prepare_docker
  stage: prepare
  image:
    name: docker
  before_script:
    - docker version
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - docker build -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
    - docker

prepare:docker:
  <<: *prepare_docker

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DTOOLCHAIN_BIN_DIR=/opt/hermit/bin -DCMAKE_INSTALL_PREFIX=/opt/hermit ..
    - make
  image: ${CI_REGISTRY_IMAGE}
  artifacts:
    paths:
      - ./build

# Stage: test
##############################################################################
test:
  stage: test
  script:
    - cd build
    - export TDIR=./local_prefix/opt/hermit/x86_64-hermit/extra
    - export FILES="$TDIR/tests/hello $TDIR/tests/hellof $TDIR/tests/hello++ $TDIR/tests/jacobi $TDIR/tests/thr_hello" #$TDIR/benchmarks/stream" #$TDIR/tests/test-malloc $TDIR/tests/test-malloc-mt"
    - export PROXY=/root/.cargo/bin/uhyve
    - for f in $FILES; do echo "check $f..."; timeout --kill-after=5m 5m $PROXY -v -c 1 -m 128M $f || exit 1; done
    - for f in $FILES; do echo "check $f..."; timeout --kill-after=5m 5m $PROXY -v -c 2 -m 128M $f || exit 1; done
  image: ${CI_REGISTRY_IMAGE}
  dependencies:
    - build
  tags:
    - privileged
